/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    products: Product;
    categories: Category;
    brands: Brand;
    news: News;
    "company-info": CompanyInfo;
    "homepage-content": HomepageContent;
    media: Media;
  };
  globals: {};
}

export interface User {
  id: string;
  role: "admin" | "product-manager";
  firstName: string;
  lastName: string;
  email: string;
  avatar?: (string | null) | Media;
  lastLogin?: string | null;
  updatedAt: string;
  createdAt: string;
  password?: string | null;
}

export interface Product {
  id: string;
  productName: string;
  slug: string;
  productCategory: (string | null) | Category;
  productBrand: (string | null) | Brand;
  productPrice: number;
  compareAtPrice?: number | null;
  skuCode: string;
  stockQuantity: number;
  productImages: {
    image: (string | null) | Media;
    alt: string;
    id?: string | null;
  }[];
  productDescription?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  shortDescription?: string | null;
  productSizes?: string | null;
  productColors?: string | null;
  specifications?: {
    material?: string | null;
    weight?: string | null;
    dimensions?: string | null;
    additionalSpecs?:
      | {
          specName: string;
          specValue: string;
          id?: string | null;
        }[]
      | null;
  };
  shippingConfig?: {
    freeShipping?: boolean | null;
    islandWideDelivery?: boolean | null;
    easyReturn?: boolean | null;
    shippingWeight?: number | null;
  };
  productStatus: "active" | "inactive" | "draft" | "out-of-stock";
  featured?: boolean | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  relatedProducts?: (string | Product)[] | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}

export interface Category {
  id: string;
  categoryName: string;
  slug: string;
  categoryDescription?: string | null;
  categoryImage?: (string | null) | Media;
  parentCategory?: (string | null) | Category;
  status: "active" | "inactive";
  displayOrder?: number | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}

export interface Brand {
  id: string;
  brandName: string;
  slug: string;
  brandDescription?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  shortDescription?: string | null;
  brandLogo?: (string | null) | Media;
  brandCoverImage?: (string | null) | Media;
  brandWebsite?: string | null;
  heritage?: string | null;
  categories?: (string | Category)[] | null;
  keyFeatures?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  partnerships?:
    | {
        partnershipName: string;
        partnershipDescription?: string | null;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  status: "active" | "inactive";
  displayOrder?: number | null;
  brandColor?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}

export interface News {
  id: string;
  postTitle: string;
  slug: string;
  postExcerpt?: string | null;
  postContent: {
    [k: string]: unknown;
  }[];
  featuredImage: (string | null) | Media;
  gallery?:
    | {
        image: (string | null) | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  author: (string | null) | User;
  publishDate: string;
  categories?:
    | {
        category:
          | "company-updates"
          | "new-partnerships"
          | "sports-events"
          | "product-launches"
          | "industry-insights"
          | "equipment-reviews"
          | "training-tips"
          | "athlete-stories";
        id?: string | null;
      }[]
    | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  readingTime?: number | null;
  featured?: boolean | null;
  status: "draft" | "published" | "archived";
  relatedProducts?: (string | Product)[] | null;
  relatedArticles?: (string | News)[] | null;
  socialSharing?: {
    enableSharing?: boolean | null;
    customSocialImage?: (string | null) | Media;
    twitterHandle?: string | null;
  };
  seoTitle?: string | null;
  seoDescription?: string | null;
  seoKeywords?:
    | {
        keyword: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}

export interface CompanyInfo {
  id: string;
  sectionName: string;
  slug: string;
  sectionContent: {
    [k: string]: unknown;
  }[];
  sectionImages?:
    | {
        image: (string | null) | Media;
        caption?: string | null;
        altText: string;
        id?: string | null;
      }[]
    | null;
  keyPoints?:
    | {
        title: string;
        description: string;
        icon?:
          | (
              | "trophy"
              | "award"
              | "star"
              | "target"
              | "users"
              | "globe"
              | "shield"
              | "truck"
              | "clock"
              | "heart"
            )
          | null;
        id?: string | null;
      }[]
    | null;
  statistics?:
    | {
        label: string;
        value: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  timeline?:
    | {
        year: string;
        title: string;
        description: string;
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  teamMembers?:
    | {
        name: string;
        position: string;
        bio?: string | null;
        photo?: (string | null) | Media;
        linkedin?: string | null;
        email?: string | null;
        id?: string | null;
      }[]
    | null;
  contactInfo?: {
    phone?: string | null;
    email?: string | null;
    whatsapp?: string | null;
    address?: string | null;
    hours?: string | null;
    socialMedia?:
      | {
          platform:
            | "facebook"
            | "instagram"
            | "twitter"
            | "linkedin"
            | "youtube"
            | "whatsapp";
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  displayOrder?: number | null;
  status: "active" | "inactive";
  lastUpdated?: string | null;
  updatedAt: string;
  createdAt: string;
}

export interface HomepageContent {
  id: string;
  contentType:
    | "hero-banner"
    | "featured-products"
    | "brand-showcase"
    | "announcement"
    | "news-highlight"
    | "testimonials"
    | "company-stats"
    | "cta-section"
    | "about-preview"
    | "sports-categories";
  contentTitle: string;
  contentSubtitle?: string | null;
  contentDescription?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  contentImage?: (string | null) | Media;
  backgroundImage?: (string | null) | Media;
  contentLink?: {
    linkText?: string | null;
    linkUrl?: string | null;
    openInNewTab?: boolean | null;
  };
  additionalLinks?:
    | {
        linkText: string;
        linkUrl: string;
        buttonStyle?: ("primary" | "secondary" | "outline" | "text") | null;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  featuredProducts?: (string | Product)[] | null;
  featuredBrands?: (string | Brand)[] | null;
  featuredNews?: (string | News)[] | null;
  statistics?:
    | {
        label: string;
        value: string;
        description?: string | null;
        icon?:
          | (
              | "trophy"
              | "award"
              | "star"
              | "target"
              | "users"
              | "globe"
              | "package"
              | "clock"
            )
          | null;
        id?: string | null;
      }[]
    | null;
  testimonials?:
    | {
        quote: string;
        author: string;
        authorTitle?: string | null;
        authorImage?: (string | null) | Media;
        rating?: number | null;
        id?: string | null;
      }[]
    | null;
  styling?: {
    backgroundColor?:
      | (
          | "white"
          | "gray-50"
          | "gray-100"
          | "blue-brand"
          | "orange-accent"
          | "dark"
          | "gradient-blue"
          | "gradient-orange"
        )
      | null;
    textColor?: ("dark" | "light" | "brand-blue" | "brand-orange") | null;
    textAlign?: ("left" | "center" | "right") | null;
    padding?: ("small" | "medium" | "large" | "xl") | null;
  };
  displayOrder: number;
  status: "active" | "inactive" | "scheduled";
  scheduledStart?: string | null;
  scheduledEnd?: string | null;
  analytics?: {
    trackClicks?: boolean | null;
    trackViews?: boolean | null;
    customTrackingId?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}

export interface Media {
  id: string;
  alt: string;
  caption?: string | null;
  description?: string | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  category?:
    | (
        | "product-images"
        | "brand-logos"
        | "news-images"
        | "company-photos"
        | "hero-images"
        | "backgrounds"
        | "icons"
        | "documents"
        | "videos"
        | "other"
      )
    | null;
  photographer?: string | null;
  usage?:
    | (
        | "website"
        | "social-media"
        | "print"
        | "email"
        | "advertising"
        | "press"
      )[]
    | null;
  copyright?: {
    owner?: string | null;
    license?:
      | (
          | "all-rights-reserved"
          | "creative-commons"
          | "public-domain"
          | "company-owned"
          | "stock-photo"
        )
      | null;
    licenseUrl?: string | null;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
    keywords?:
      | {
          keyword: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    desktop?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
